# Generated by Django 3.1.6 on 2021-06-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmg', '0003_auto_20210613_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
